FROM mariadb:latest

#FROM mysql:latest

#RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf && a2enmod rewrite && a2dissite 000-default && service apache2 restart

#RUN docker-php-ext-install mysql